version: '2.1'

services:
  mysql:
    container_name: keep_in_touch_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: touch_root
      MYSQL_DATABASE: touch_db
      MYSQL_USER: touch_user
      MYSQL_PASSWORD: touch_passwort
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mobile-api-container:
    container_name: keep_in_touch_api
    build: ./rest_controller
    links:
      - mysql
    restart: on-failure
    volumes: 
      - ./data/keep_in_touch_api
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
